### PR TITLE
Handle retry state

### PR DESCRIPTION
**Pull request by ztamas83**
I built this on top of @toini's PR as the backoff and jitter is obviously needed.
Tested without pyTibber so far and it recovers nicely without spike in CPU.

### CODE REVIEW

**Comment by toini** [comment]
Looks good!

**Comment by ztamas83** [comment]
Alright I think I managed to get the subscriptions working too. My head is spinning so I appreciate the comments on the code, it's probably not perfect.

The code targets both #32 and #33 .
If subscriptions are tried before the connection is running they just get timed out and never subscribed. I defer the subscriptions until the socket is available.

I also changed the subscription ID:s in order not to interfere with other manager instances. Not sure if that's required.

**Comment by ztamas83** [comment]
> Alright I think I managed to get the subscriptions working too. My head is spinning so I appreciate the comments on the code, it's probably not perfect.
> 
> The code targets both #32 and #33 . If subscriptions are tried before the connection is running they just get timed out and never subscribed. I defer the subscriptions until the socket is available.
> 
> I also changed the subscription ID:s in order not to interfere with other manager instances. Not sure if that's required.

After some thoughts it's better to keep the two things separated, too big of a change together. Handling the retry state and prevent the loop is priority I believe. So this PR targets #32 only.

**Comment by ztamas83** [comment]
Replaced by #37, it's a rebase on master

**Pull request closed without merging**
